[workspace]
members = [
    "d4-arjun-sys",
    "d4-cadiback-sys",
    "d4-cadical-sys",
    "d4-cryptominisat-sys",
    "d4-glucose-sys",
    "d4-gpmc-sys",
    "d4-oxide",
    "d4-sbva-sys",
]

resolver = "2"
