name: CI

on:
  - push

jobs:
  Format:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Format
        run: cargo fmt --check

  Lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Nix
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Lint
        run: nix develop --command cargo clippy -- --deny warnings

  Build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Nix
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Build
        run: nix develop --command cargo build
