name: CI

on:
  - push

env:
  CARGO_TERM_COLOR: always
  CMAKE_GENERATOR: Ninja
  CMAKE_C_COMPILER_LAUNCHER: sccache
  CMAKE_CXX_COMPILER_LAUNCHER: sccache
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: true

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Format
        run: cargo fmt --check

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: sudo apt-get install ninja-build libtbb-dev libhwloc-dev libboost-program-options-dev
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Setup environment
        run: |
          echo MTKAHYPAR_DIR=$(mktemp -d) >> $GITHUB_ENV
      - name: Build Mt-KaHyPar
        run: |
          cd $(mktemp -d)
          git clone --recursive https://github.com/kahypar/mt-kahypar.git .
          git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
          cmake -B build -D CMAKE_INSTALL_PREFIX=$MTKAHYPAR_DIR -D MT_KAHYPAR_DISABLE_BOOST=true
          cmake --build build --target mtkahypar
          cmake --install build
      - name: Lint
        run: cargo clippy -- --deny warnings

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: sudo apt-get install ninja-build libtbb-dev libhwloc-dev libboost-program-options-dev
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Setup environment
        run: |
          echo MTKAHYPAR_DIR=$(mktemp -d) >> $GITHUB_ENV
      - name: Build Mt-KaHyPar
        run: |
          cd $(mktemp -d)
          git clone --recursive https://github.com/kahypar/mt-kahypar.git .
          git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
          cmake -B build -D CMAKE_INSTALL_PREFIX=$MTKAHYPAR_DIR
          cmake --build build --target mtkahypar
          cmake --install build
      - name: Build
        run: cargo build
