name: CI

on:
  - push

jobs:
  Format:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Format
        run: cargo fmt --check

  Lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Nix
        uses: cachix/install-nix-action@v30
      - name: Cache
        uses: cachix/cachix-action@v15
        with:
          name: softvare-group
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Lint
        run: nix develop --command cargo clippy -- --deny warnings

  Build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Nix
        uses: cachix/install-nix-action@v30
      - name: Cache
        uses: cachix/cachix-action@v15
        with:
          name: softvare-group
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix develop --command cargo build
